---
# tasks file for deploy_apche_web

- name: Check and view Linux Version
  debug: var=ansible_os_family

- block: #=====BLOCK FOR REDHAT
    - name: Procces installing web server for RedHat
      yum: name=httpd state=latest
      notify: Restart Apache Web Server(REDHAT)
    - name: Start Web Server
      service: name=httpd state=started enabled=yes
  when: ansible_os_family == "RedHat"


- block: #=====BLOCK FOR DEBIAN=====
    - name: Procces installing web server for Ubuntu/Debian
      apt: name=apache2 state=latest
      notify: Restart Apache Web Server(DEBIAN)
    - name: Start Web Server
      service: name=apache2 state=started enabled=yes
  when: ansible_os_family == "Debian"


- name: Generate INDEX.html file
  template: src=index.j2 dest={{ destin_folder }}/index.html  mode=0555
  notify:
    - Restart Apache RedHat
    - Restart Apache Debian

- name: Copy homepage file to webserver
  copy: src={{ item }} dest={{ destin_folder }} mode=0555
  loop:
    - "text1.txt"
    - "text2.txt"

