---
- name: Install Apache2 Web Server
  hosts: AWS
  become: yes
  
  tasks:

   - name: Check and view Linux Version
     debug: var=ansible_os_family

   - name: Procces installing web server for RedHat
     yum: name=httpd state=latest
     notify: Restart Apache Web Server(REDHAT)
   - name: Start Web Server
     service: name=httpd state=started enabled=yes
     when: ansible_os_family == "RedHat"
            
   - name: Procces installing web server for Ubuntu/Debian
     apt: name=apache2 state=latest
     notify: Restart Apache Web Server(DEBIAN)
   - name: Start Web Server
     service: name=apache2 state=started enabled=yes
     when: ansible_os_family == "Debian"
