---
- name: Install Jenkins CI/CD
  hosts: JENKINS
  become: true

  tasks:

   - name: Check and view Linux Version
     debug: var=ansible_os_family

   - block: #=====BLOCK FOR REDHAT
       - name: Procces installing web server for RedHat
         yum: name=jenkins state=latest
         notify: Restart Apache Web Server(REDHAT)
       - name: Start JENKINS
         service: name=jenkins state=started enabled=yes
     when: ansible_os_family == "RedHat"


   - block: #=====BLOCK FOR DEBIAN=====

       - name: Install JDK8
         apt: name=openjdk-8-jdk state=latest
         
       - name: Procces installing Jenkins for Ubuntu/Debian
         apt: name=jenkins state=latest
         when: ansible_os_family == "Debian"
         notify: Start Jenkins (DEBIAN)
       - name: Start JENKINS
         service: name=jenkins state=started enabled=yes
     when: ansible_os_family == "Debian"

